import os
import warnings
import logging

# Must be set before any library that lazily imports transformers is loaded
os.environ["TRANSFORMERS_VERBOSITY"] = "error"
os.environ["TOKENIZERS_PARALLELISM"] = "false"
warnings.filterwarnings("ignore")
logging.getLogger("transformers").setLevel(logging.ERROR)
logging.getLogger("huggingface_hub").setLevel(logging.ERROR)

import io
import base64
import tempfile
import streamlit as st
from dotenv import load_dotenv
from huggingface_hub import InferenceClient
from langchain_chroma import Chroma
from langchain_ollama import OllamaEmbeddings
from feature_extraction_rag import predict_single_image

load_dotenv()

CHROMA_PATH = r"./RAG_app/chroma_langchain_db"

SYSTEM_PROMPT = """You are a medical assistant specialized in breast imaging and radiology. 
    You answer questions strictly based on the BI-RADS (Breast Imaging Reporting and Data System) guidelines provided to you as context.

    Rules:
    - Only answer based on the provided context, do not use outside knowledge
    - If the answer is not found in the context, say "I cannot find this information in the BI-RADS guidelines"
    - Be precise and clinical in your language
    - Do not provide personal medical advice or diagnoses
    - If a question is ambiguous, ask for clarification before answering
    - Do not reorder or reinterpret the categories, present them exactly as described in the context"""

IMAGE_SYSTEM_PROMPT = """You are a medical assistant specialized in breast imaging and radiology.
    You will be provided with extracted radiomics features from a breast mass, along with the BI-RADS guidelines as context.

    Your task:
    - Predict the most appropriate BI-RADS category (0-6) for the mass
    - Provide a thorough clinical rationale explaining why you assigned that category
    - Reference specific features (shape, margin, sphericity) in your reasoning
    - Ground your prediction strictly in the BI-RADS guidelines provided in the context
    - Be precise and clinical in your language

    Important: Always end your response with the following disclaimer, word for word:
    ---
    ⚠️ DISCLAIMER: This prediction is generated by an AI model for research purposes only. 
    It is not a medical diagnosis and is not legally binding. 
    Always consult a qualified radiologist or clinician before making any clinical decision."""

st.set_page_config(page_title="BI-RADS Assistant", page_icon="🩺", layout="centered")

st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;500&family=DM+Mono:wght@300;400&family=Instrument+Sans:wght@300;400;500&display=swap');

*, *::before, *::after { box-sizing: border-box; }

body,
.stApp,
[data-testid="stAppViewContainer"],
[data-testid="stMain"],
section[data-testid="stMain"] > div {
    background-color: #F7F5F0 !important;
    font-family: 'Instrument Sans', sans-serif !important;
}

[data-testid="stHeader"],
[data-testid="stToolbar"] {
    background-color: #F7F5F0 !important;
    border-bottom: none !important;
}

[data-testid="stMainBlockContainer"] {
    max-width: 780px !important;
    padding: 3rem 2rem 6rem !important;
}

h1 {
    font-family: 'Playfair Display', serif !important;
    font-size: 2.1rem !important;
    font-weight: 500 !important;
    color: #1A1814 !important;
    letter-spacing: -0.5px !important;
    line-height: 1.2 !important;
    margin-bottom: 0.2rem !important;
}

p {
    font-family: 'Instrument Sans', sans-serif !important;
    color: #7A7467 !important;
    font-size: 0.875rem !important;
    font-weight: 300 !important;
    letter-spacing: 0.01em !important;
}

hr {
    border: none !important;
    border-top: 1px solid #E2DDD6 !important;
    margin: 1.5rem 0 2rem !important;
}

/* ── Chat messages ── */
[data-testid="stChatMessage"] {
    background-color: transparent !important;
    border: none !important;
    border-radius: 0 !important;
    padding: 0.25rem 0 !important;
    margin-bottom: 0 !important;
    box-shadow: none !important;
}

div[data-testid="stChatMessage"]:has([data-testid="chatAvatarIcon-user"]) {
    background-color: #EDEBE5 !important;
    border-radius: 16px 16px 4px 16px !important;
    padding: 0.85rem 1.1rem !important;
    margin-left: 3rem !important;
    margin-bottom: 1rem !important;
}

div[data-testid="stChatMessage"]:has([data-testid="chatAvatarIcon-assistant"]) {
    background-color: #FFFFFF !important;
    border: 1px solid #E2DDD6 !important;
    border-radius: 16px 16px 16px 4px !important;
    padding: 0.85rem 1.1rem !important;
    margin-right: 3rem !important;
    margin-bottom: 1rem !important;
}

[data-testid="stChatMessageContent"] p {
    font-family: 'Instrument Sans', sans-serif !important;
    color: #1A1814 !important;
    font-size: 0.93rem !important;
    line-height: 1.75 !important;
    font-weight: 300 !important;
    margin: 0 !important;
}

[data-testid="chatAvatarIcon-user"],
[data-testid="chatAvatarIcon-assistant"] {
    background-color: #1A1814 !important;
    border-radius: 50% !important;
    color: #F7F5F0 !important;
}

/* ── Chat input ── */
[data-testid="stChatInput"] {
    background-color: #FFFFFF !important;
    border: 1px solid #C8C3BB !important;
    border-radius: 12px !important;
    box-shadow: 0 2px 12px rgba(26, 24, 20, 0.06) !important;
}

[data-testid="stChatInput"]:focus-within {
    border-color: #1A1814 !important;
    box-shadow: 0 2px 16px rgba(26, 24, 20, 0.1) !important;
}

[data-testid="stChatInput"] textarea {
    font-family: 'Instrument Sans', sans-serif !important;
    font-size: 0.9rem !important;
    font-weight: 300 !important;
    color: #1A1814 !important;
    background-color: transparent !important;
    caret-color: #1A1814 !important;
}

[data-testid="stChatInput"] textarea::placeholder {
    color: #B0AA9F !important;
    font-style: italic !important;
    font-size: 0.875rem !important;
}

[data-testid="stChatInputSubmitButton"] button {
    background-color: #1A1814 !important;
    border-radius: 8px !important;
    color: #F7F5F0 !important;
}

/* ── File uploader → plain + circle, pinned inside the chat input bar ── */
[data-testid="stFileUploader"] {
    position: fixed !important;
    bottom: 42px !important;
    left: max(1.2rem, calc(50vw - 371px)) !important;
    z-index: 1001 !important;
    width: 36px !important;
    height: 36px !important;
    margin: 0 !important;
    padding: 0 !important;
    background: transparent !important;
    border: none !important;
    overflow: visible !important;
}
[data-testid="stFileUploader"] label,
[data-testid="stFileUploader"] > div > label { display: none !important; }
[data-testid="stFileUploader"] section,
[data-testid="stFileUploader"] section > div {
    background: transparent !important;
    border: none !important;
    padding: 0 !important;
    margin: 0 !important;
    width: 36px !important;
    height: 36px !important;
    overflow: visible !important;
}
[data-testid="stFileUploaderDropzone"] {
    background: transparent !important;
    border: none !important;
    padding: 0 !important;
    margin: 0 !important;
    width: 36px !important;
    height: 36px !important;
    min-width: 0 !important;
    overflow: visible !important;
    display: flex !important;
    align-items: center !important;
    justify-content: center !important;
}
[data-testid="stFileUploaderDropzoneInstructions"] { display: none !important; }
[data-testid="stFileUploaderFileList"],
[data-testid="stFileUploaderFile"] { display: none !important; }
/* The browse-files button → + circle */
[data-testid="stFileUploaderDropzone"] button {
    width: 36px !important;
    height: 36px !important;
    min-height: 0 !important;
    min-width: 0 !important;
    border-radius: 50% !important;
    background: #F7F5F0 !important;
    border: 1.5px solid #C8C3BB !important;
    padding: 0 !important;
    margin: 0 !important;
    box-shadow: none !important;
    cursor: pointer !important;
    font-size: 0 !important;
    color: transparent !important;
    line-height: 1 !important;
    display: flex !important;
    align-items: center !important;
    justify-content: center !important;
    transition: border-color 0.15s, background 0.15s !important;
}
[data-testid="stFileUploaderDropzone"] button * { display: none !important; }
[data-testid="stFileUploaderDropzone"] button:hover {
    border-color: #1A1814 !important;
    background: #EDEBE5 !important;
}
[data-testid="stFileUploaderDropzone"] button::after {
    content: "+" !important;
    display: block !important;
    font-size: 1.4rem !important;
    font-weight: 400 !important;
    color: #7A7467 !important;
    line-height: 1 !important;
    pointer-events: none !important;
}
[data-testid="stFileUploaderDropzone"] button:hover::after { color: #1A1814 !important; }

/* Indent chat textarea so text doesn't start under the + button */
[data-testid="stChatInput"] textarea { padding-left: 50px !important; }

/* ── Attachment X button: fixed near the chip ── */
[data-testid="stButton"] {
    position: fixed !important;
    bottom: 96px !important;
    left: calc(max(1.2rem, calc(50vw - 371px)) + 270px) !important;
    z-index: 1001 !important;
    width: 26px !important;
    height: 26px !important;
    min-height: 0 !important;
}
[data-testid="stButton"] button {
    background: #F7F5F0 !important;
    border: 1px solid #C8C3BB !important;
    border-radius: 50% !important;
    width: 26px !important;
    height: 26px !important;
    min-height: 0 !important;
    padding: 0 !important;
    font-size: 0.7rem !important;
    color: #7A7467 !important;
    box-shadow: none !important;
    line-height: 1 !important;
}

/* Image thumbnail inside user bubble */
[data-testid="stChatMessage"] img {
    max-width: 200px !important;
    max-height: 160px !important;
    border-radius: 8px !important;
    display: block !important;
    margin-bottom: 6px !important;
    object-fit: cover !important;
}

/* ── Bottom bar background ── */
section[data-testid="stBottom"],
section[data-testid="stBottom"] > div,
section[data-testid="stBottom"] > div > div,
.stBottom, .stBottom > div {
    background-color: #F7F5F0 !important;
    border-top: none !important;
}

/* ── Spinner ── */
[data-testid="stSpinner"] p {
    font-family: 'DM Mono', monospace !important;
    font-size: 0.75rem !important;
    color: #7A7467 !important;
    letter-spacing: 0.05em !important;
}

::-webkit-scrollbar { width: 4px; }
::-webkit-scrollbar-track { background: transparent; }
::-webkit-scrollbar-thumb { background: #C8C3BB; border-radius: 2px; }
</style>
""", unsafe_allow_html=True)

# ── Header ──
st.markdown("""
<div style="margin-bottom: 0.25rem;">
  <span style="font-family: 'DM Mono', monospace; font-size: 0.7rem; letter-spacing: 0.15em; text-transform: uppercase; color: #7A7467; background: #EDEBE5; padding: 3px 8px; border-radius: 4px;">Radiology · RAG</span>
</div>
<h1>BI-RADS Assistant</h1>
<p style="margin-top: 0.4rem;">Clinical answers grounded in the ACR BI-RADS guidelines</p>
""", unsafe_allow_html=True)

st.divider()


@st.cache_resource
def load_index():
    embeddings = OllamaEmbeddings(model="mxbai-embed-large")
    vector_store = Chroma(
        collection_name="bi_rads_collection",
        embedding_function=embeddings,
        persist_directory=CHROMA_PATH,
    )
    return vector_store


@st.cache_resource
def load_client():
    return InferenceClient(
        model="meta-llama/Llama-3.1-8B-Instruct",
        token="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"
    )


def get_augmented_context(prompt, vector_store):
    results = vector_store.similarity_search(prompt, k=6)
    return "\n\n".join([res.page_content for res in results])


def ask(user_question, vector_store, client, image_path=None):
    context = get_augmented_context(user_question, vector_store)
    if image_path:
        mass_info = predict_single_image(image_path)
        response = client.chat_completion(
            messages=[
                {"role": "system", "content": IMAGE_SYSTEM_PROMPT},
                {"role": "user", "content": f"Context: {context}\n\nQuestion: {user_question}\n\nMass Info: {mass_info}"}
            ]
        )
    else:
        response = client.chat_completion(
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": f"Context: {context}\n\nQuestion: {user_question}"}
            ]
        )
    return response.choices[0].message.content


# ── Session state ──
if "messages" not in st.session_state:
    st.session_state.messages = []
if "pending_bytes" not in st.session_state:
    st.session_state.pending_bytes = None
if "pending_name" not in st.session_state:
    st.session_state.pending_name = None
if "uploader_key" not in st.session_state:
    st.session_state.uploader_key = 0

vector_store = load_index()
client = load_client()

# ── Welcome state ──
if not st.session_state.messages:
    st.markdown("""
    <div style="border: 1px solid #E2DDD6; border-radius: 12px; padding: 1.5rem 1.75rem; background: #FFFFFF; margin-bottom: 2rem;">
        <p style="margin: 0 0 0.75rem; color: #1A1814; font-weight: 500; font-size: 0.9rem;">Example questions</p>
        <ul style="margin: 0; padding-left: 1.1rem; display: flex; flex-direction: column; gap: 0.4rem;">
            <li style="color: #7A7467; font-size: 0.85rem;">What does BI-RADS category 4 mean?</li>
            <li style="color: #7A7467; font-size: 0.85rem;">What management is recommended for a BI-RADS 3 finding?</li>
            <li style="color: #7A7467; font-size: 0.85rem;">Describe the features of a benign-appearing mass on ultrasound.</li>
            <li style="color: #7A7467; font-size: 0.85rem;">What are the subcategories of BI-RADS 4?</li>
        </ul>
    </div>
    """, unsafe_allow_html=True)

# ── Chat history ──
for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        if msg.get("image_bytes"):
            st.image(msg["image_bytes"], width=200)
        st.markdown(msg["content"])

# ── Attachment preview (shown above the chat input when a file is pending) ──
if st.session_state.pending_bytes:
    thumb_b64 = base64.b64encode(st.session_state.pending_bytes).decode()
    st.markdown(f"""
    <div style="position:fixed;bottom:88px;left:max(1.2rem, calc(50vw - 371px));
                z-index:999;display:inline-flex;align-items:center;gap:10px;
                background:#fff;border:1px solid #E2DDD6;border-radius:10px;
                padding:8px 12px;box-shadow:0 2px 8px rgba(26,24,20,0.07);">
      <img src="data:image/png;base64,{thumb_b64}"
           style="width:48px;height:48px;object-fit:cover;border-radius:6px;flex-shrink:0;"/>
      <span style="font-size:0.82rem;color:#1A1814;
                   font-family:'Instrument Sans',sans-serif;
                   max-width:200px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;">
        {st.session_state.pending_name}
      </span>
    </div>
    """, unsafe_allow_html=True)
    if st.button("✕", key="rm_attachment"):
        st.session_state.pending_bytes = None
        st.session_state.pending_name = None
        st.session_state.uploader_key += 1
        st.rerun()

# ── + button (file uploader, fixed-positioned inside the chat input bar via CSS) ──
uploaded_file = st.file_uploader(
    "Upload image",
    type=["png", "jpg", "jpeg"],
    label_visibility="collapsed",
    key=f"fu_{st.session_state.uploader_key}",
)
# Only store when a NEW file is selected — avoids infinite rerun loop
if uploaded_file is not None and uploaded_file.name != st.session_state.pending_name:
    st.session_state.pending_bytes = uploaded_file.read()
    st.session_state.pending_name = uploaded_file.name
    st.rerun()

# ── Chat input ──
user_input = st.chat_input("Ask about BI-RADS guidelines…")

if user_input and user_input.strip():
    image_bytes = st.session_state.pending_bytes
    image_name = st.session_state.pending_name

    st.session_state.pending_bytes = None
    st.session_state.pending_name = None
    st.session_state.uploader_key += 1

    st.session_state.messages.append({
        "role": "user",
        "content": user_input,
        "image_bytes": image_bytes,
    })
    with st.chat_message("user"):
        if image_bytes:
            st.image(image_bytes, width=200)
        st.markdown(user_input)

    with st.chat_message("assistant"):
        with st.spinner("Retrieving from guidelines…"):
            try:
                image_path = None
                if image_bytes:
                    suffix = os.path.splitext(image_name)[1] if image_name else ".png"
                    with tempfile.NamedTemporaryFile(delete=False, suffix=suffix) as tmp:
                        tmp.write(image_bytes)
                        image_path = tmp.name
                answer = ask(user_input, vector_store, client, image_path=image_path)
            except Exception as e:
                answer = f"Error retrieving answer: {e}"
        st.markdown(answer)

    st.session_state.messages.append({"role": "assistant", "content": answer})
    # Force a rerun so the file uploader is re-created with the new key,
    # ensuring the user can upload another image immediately.
    st.rerun()